fix: Use functools.partial for jax.jit with static_argnames
- Change from @jax.jit(static_argnames=[...]) to @partial(jax.jit, static_argnames=[...])
- This syntax is compatible with Python 3.9+ and all JAX versions
- Resolves \"TypeError: jit() missing 1 required positional argument: 'fun'\"